### ISSUE TITLE
leg_detector from ROS

### ISSUE THREAD

**Issue by jnisa** [hcrlab/wiki#1]
Hi,

I have a trouble when I try to visualize the detection results of the leg_detector.
After the following command, roslaunch leg_detector leg_detector.launch, I get the following error in the terminal,
https://imgur.com/EpOQIR2
Do you know how to solve this issue?
Thanks in advance

**Comment by nickswalker** [comment]
You'll probably have better luck posting on the repo were leg_detector is developed: https://github.com/wg-perception/people

But at a glance, looks like there's a filter that's waiting for a particular transform to become available before letting messages through. Probably have to run something else (simulator, since it's asking for odom data) before the code can proceed.
